name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
        pip install -e .
    
    - name: Run unit tests
      run: |
        pytest tests/test_unit.py -v

    - name: Run integration tests
      env:
        OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      run: |
        pytest tests/test_integration.py -v
      if: ${{ secrets.OMDB_API_KEY != '' }}  # Only run if API key is available

    - name: Build Docker image
      run: docker build -t movie-aggregator .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag movie-aggregator ${{ secrets.DOCKER_HUB_USERNAME }}/movie-aggregator:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/movie-aggregator:latest
